### PR TITLE
Plugin style livewire tool

### PR DESCRIPTION
**Pull request by hkmoon**
LiveWire tool is now plugin instead of macro.
It is easy to be installed in Fiji as a plugin.

### CODE REVIEW

**Comment by dscho** [comment]
Please note that I accepted a not-quite-polished PR this time around, in the interest of time. The problems I noted in my comments are basically the same as I pointed out in the PR for the nar-maven-plugin earlier: commits really should contain a coherent story, each commit reflecting a change that can be described [in a clear, short message](http://tbaggery.com/2008/04/19/a-note-about-git-commit-messages.html) (the commit message's subject) frequently accompanied by background information that offers the rationale for the change, possibly a discussion about different implementation strategies that were rejected over the current implementation, essentially: information that cannot be easily deduced from the diff but that is helpful nevertheless to understand the commit fully (all of this information naturally goes into the commit message's body).

Please keep in mind that these rules are not self-serving, but rather enable a fruitful collaboration with others. In fact, well-crafted commit messages and _nice_ commit histories are an important part of the communication between successful developers.

**Comment by dscho** [comment]
I added quite a few changes, in the development style I encourage you to imitate.

There is a problem, though: neither current code does not do anything when the `TestDrive`'s `main` method is called, neither do the `main` methods I removed (and that were introduced with the merge of this PR) do anything. The Clown sample loads alright, but the tool does not work. @hkmoon do you have any idea why?

**Comment by hkmoon** [comment]
I used argv: program arguments for loading images in main. When you load the Clown image, the tool should be closed and opened. Probably, ActionListeners are not managed in multiple image windows. I am going to figure it out. Also, Benoit pointed out some bugs in my version.

I cannot thank you more because your comments seem to be written in a very clear connotation. Even though it is not easy to change coding habits. It won't take long for me to learn it in order to satisfy mutual coders.

If you do not think that my request should be revised according to the concerns, feel free to reject it. I would be happy to change the way I used to work.

**Comment by dscho** [comment]
> I used argv: program arguments for loading images in main.

Yes, I saw that, but I found it more convenient to follow the convention that Fiji.app lives in $HOME/Desktop, and most power users of Fiji I know cache the sample images, so the clown image will be available even if you happen to sit in a plane or rush through a tunnel inside a train.

> Also, Benoit pointed out some bugs in my version.

Who is Benoit.

> If you do not think that my request should be revised according to the concerns, feel free to reject it.

Oh, but I merged it already! ;-) Thank you!

**Comment by hkmoon** [comment]
> I used argv: program arguments for loading images in main.
> 
> Yes, I saw that, but I found it more convenient to follow the convention that Fiji.app lives in $HOME/Desktop, and most power users of Fiji I know cache the sample images, so the clown image will be available even if you happen to sit in a plane or rush through a tunnel inside a train.
> 
> Oh, that’s great. I have to move Fiji.app in $HOME/Desktop from “Applications”!
> Also, Benoit pointed out some bugs in my version.
> 
> Who is Benoit.
> 
> He is working in BioImage Informatics service facility at MPI-CBG. He knows even Jean-Yves who praised you a lot! You will meet him when the time comes. ;)
> If you do not think that my request should be revised according to the concerns, feel free to reject it.
> 
> Oh, but I merged it already! ;-) Thank you!
> 
> I thank you!

**Comment by hkmoon** [comment]
> Please note that I accepted a not-quite-polished PR this time around, in the interest of time. The problems I noted in my comments are basically the same as I pointed out in the PR for the nar-maven-plugin earlier: commits really should contain a coherent story, each commit reflecting a change that can be described in a clear, short message (the commit message's subject) frequently accompanied by background information that offers the rationale for the change, possibly a discussion about different implementation strategies that were rejected over the current implementation, essentially: information that cannot be easily deduced from the diff but that is helpful nevertheless to understand the commit fully (all of this information naturally goes into the commit message's body).

I have seen your series of commits in Live_Wire. They told me short message with reasonable explanation is very important for communication/understanding in collaboration. That is the most important thing in open source projects. I will try to follow your way.

> Please keep in mind that these rules are not self-serving, but rather enable a fruitful collaboration with others. In fact, well-crafted commit messages and nice commit histories are an important part of the communication between successful developers.

"well-crafted commit messages and nice commit histories" should be kept in mind. Thank you for sharing your precious wisdom and kind advices!

**Pull request merged**
